app.controller("myCtrl", ['$scope', function($scope) { 
  $scope.title = 'Vishal Singh'; 
  $scope.name = "Vishal singh"
  $scope.addr = "Staff quarter no. 28 "
  $scope.addr1 = "Meerut college meerut"
  $scope.mobi = "8171096014"
  $scope.email = "Vishalsinghmrt94@gmail.com"
  $scope.about = "About Me"
  $scope.project1 = "This is a technical website which providing information about new technology and gadget coming, it is a simple static website made by using technologies, "
  $scope.project2 = "This is a embedded system project based on a persistance of vision, by this we can display a massege on a revolving  single LED strip, made by using arduino microcontroller, and a 1000rpm Dc motor"
  $scope.project3 = "This is my own information website, Here you can know about my project my qualifiction, my hobbies and intrest, and other information, you can also send me a message by this, made by using  "
  $scope.project4 = "This blog on my shayri and poetry, as I love to do shayri & poetry, shayri is my hobby, this is in hindi and hinglish"
  $scope.aboutPara = "I am vishal singh, I belong from meerut, I am persuing my B.tech from KIET group of Institution, my Intrest field is Web Devlopment, and meachine learning, talking about my professional skils, I make some project like, techvishal.com, My.info, Propeller Clock, and robo-car, "
  $scope.aboutPara1 = "1.techvishal.com is a simple information providing static technical website, made by using technology HTML, CSS, Bootstrap, php."
  $scope.aboutPara2 = "2.My.info is my personal online profile here you can read a brief about me regarding my profesional life, made by using technology HTML, CSS Bootstrap, Angular.js, Expres.js."
  $scope.aboutPara3 = "3.Propeller Clock is my embedded system project, propeller Clock is a basically based on a persistance of vission, In it we can display the any message text on a single strip of a Revolving LED, Using the feature of Persistance Of Vission, A message text can be any static or dynamic, Using Arduino microcontroller."
  $scope.aboutPara4 = "4.Robo-Car is a simple robo racing car, made by using DPDT switches,"   
  $scope.aboutPara5 = "I have a decent knowledge of C-language, HTML, CSS, Bootstrap, Angularjs, and little bit about embedded system"
  $scope.aboutPara6 = "I am a hardworking, selfmotivated, creative, type of a persone focus toward my aim , I am good in a mannaging thing's as I am a captain of my school senior and junior scout team continuously 4 year(2009-2012), I am a Discipline and Event Coordinator in my college annual fest(2017), and I am also a placement coordinator in many companies visiting my college campus in year 2016 and 2017 "
  $scope.aboutPara7 = "My hobbies are writting shayri and poetry on which I have a blog diarytear.blogspot.in, writing short stories, like to watch Tv shows on a science and technology, listening music and suffering on a internet"
}]);